### ISSUE TITLE
PermissionError need help 

### ISSUE THREAD

**Issue by MrXploisLite** [DwrldDev/Fivem-Server-Unban#3]
File exist
Picture exists
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\romyr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "C:\Fivem-Server-Unban-main\Cleaner.py", line 150, in xbox
    f = open(file_path, 'a')
        ^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'C:\\WINDOWS\\System32\\drivers\\etc'

**Comment by DwrldDev** [comment]
Try running the program as admin to get the permissions needed, as admin is needed to block xbox live connections as it will write the following i put below into your host file, or you can manually put it in the host file

it can only block it from linking to your next set of identifers

to block it, add this text to your windows hosts file and then use all new identifers

```
127.0.0.1 xboxlive.com
127.0.0.1 user.auth.xboxlive.com
127.0.0.1 presence-heartbeat.xboxlive.com
```
